version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: studynotion-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE:-studynotion}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-gateway:
    build:
      context: ./microservices
      dockerfile: api-gateway/Dockerfile
    container_name: studynotion-api-gateway
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PAYMENT_SERVICE_URL=http://payment-service:3002
      - COURSE_SERVICE_URL=http://course-service:3003
      - PROFILE_SERVICE_URL=http://profile-service:3004
      - RATING_SERVICE_URL=http://rating-service:3005
      - MEDIA_SERVICE_URL=http://media-service:3006
      - NOTIFICATION_SERVICE_URL=http://notification-service:3007
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  auth-service:
    build:
      context: ./microservices
      dockerfile: auth-service/Dockerfile
    container_name: studynotion-auth-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URL=mongodb://${MONGODB_USERNAME:-admin}:${MONGODB_PASSWORD:-password123}@mongodb:27017/${MONGODB_DATABASE:-studynotion}?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-here}
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_USER=${MAIL_USER:-your-email@gmail.com}
      - MAIL_PASS=${MAIL_PASS:-your-app-password}
      - BCRYPT_SALT_ROUNDS=12
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  payment-service:
    build:
      context: ./microservices
      dockerfile: payment-service/Dockerfile
    container_name: studynotion-payment-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URL=mongodb://${MONGODB_USERNAME:-admin}:${MONGODB_PASSWORD:-password123}@mongodb:27017/${MONGODB_DATABASE:-studynotion}?authSource=admin
      - RAZORPAY_KEY=${RAZORPAY_KEY:-your-razorpay-key}
      - RAZORPAY_SECRET=${RAZORPAY_SECRET:-your-razorpay-secret}
      - COURSE_SERVICE_URL=http://course-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3007
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  course-service:
    build:
      context: ./microservices
      dockerfile: course-service/Dockerfile
    container_name: studynotion-course-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGODB_URL=mongodb://${MONGODB_USERNAME:-admin}:${MONGODB_PASSWORD:-password123}@mongodb:27017/${MONGODB_DATABASE:-studynotion}?authSource=admin
      - MEDIA_SERVICE_URL=http://media-service:3006
      - RATING_SERVICE_URL=http://rating-service:3005
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  profile-service:
    build:
      context: ./microservices
      dockerfile: profile-service/Dockerfile
    container_name: studynotion-profile-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3004
      - MONGODB_URL=mongodb://${MONGODB_USERNAME:-admin}:${MONGODB_PASSWORD:-password123}@mongodb:27017/${MONGODB_DATABASE:-studynotion}?authSource=admin
      - MEDIA_SERVICE_URL=http://media-service:3006
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  rating-service:
    build:
      context: ./microservices
      dockerfile: rating-service/Dockerfile
    container_name: studynotion-rating-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3005
      - MONGODB_URL=mongodb://${MONGODB_USERNAME:-admin}:${MONGODB_PASSWORD:-password123}@mongodb:27017/${MONGODB_DATABASE:-studynotion}?authSource=admin
      - COURSE_SERVICE_URL=http://course-service:3003
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  media-service:
    build:
      context: ./microservices
      dockerfile: media-service/Dockerfile
    container_name: studynotion-media-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3006
      - MONGODB_URL=mongodb://${MONGODB_USERNAME:-admin}:${MONGODB_PASSWORD:-password123}@mongodb:27017/${MONGODB_DATABASE:-studynotion}?authSource=admin
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME:-your-cloud-name}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY:-your-api-key}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET:-your-api-secret}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  notification-service:
    build:
      context: ./microservices
      dockerfile: notification-service/Dockerfile
    container_name: studynotion-notification-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3007
      - MONGODB_URL=mongodb://${MONGODB_USERNAME:-admin}:${MONGODB_PASSWORD:-password123}@mongodb:27017/${MONGODB_DATABASE:-studynotion}?authSource=admin
      - MAIL_HOST=${MAIL_HOST:-smtp.gmail.com}
      - MAIL_USER=${MAIL_USER:-your-email@gmail.com}
      - MAIL_PASS=${MAIL_PASS:-your-app-password}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend-microservice
      dockerfile: Dockerfile
    container_name: studynotion-frontend
    restart: unless-stopped
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:4000/api/v1
    depends_on:
      api-gateway:
        condition: service_healthy
    networks:
      - studynotion-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  studynotion-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mongodb_data:
    driver: local