apiVersion: v1
kind: Service
metadata:
  name: rating-service
  labels:
    app: studynotion
    component: rating-service
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
      name: http
  selector:
    app: studynotion
    component: rating-service
