apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: studynotion
  labels:
    app: rating-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3005
    protocol: TCP
    name: http
  selector:
    app: rating-service
