apiVersion: v1
kind: Service
metadata:
  name: course-service
  labels:
    app: course-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: course-service
