apiVersion: v1
kind: Service
metadata:
  name: course-service
  labels:
    app: studynotion
    component: course-service
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app: studynotion
    component: course-service
