apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        component: microservice
    spec:
      containers:
      - name: payment-service
        image: studynotion-payment-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: NODE_ENV
        - name: PORT
          value: "3002"
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: MONGODB_URI_PAYMENT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: JWT_SECRET
        - name: RAZORPAY_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: RAZORPAY_KEY_ID
        - name: RAZORPAY_SECRET
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: RAZORPAY_KEY_SECRET
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: API_BASE_URL
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
