# Auth Service Deployment
# Handles user authentication, registration, and JWT token management
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: studynotion
    component: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studynotion
      component: auth-service
  template:
    metadata:
      labels:
        app: studynotion
        component: auth-service
    spec:
      containers:
        - name: auth-service
          image: studynotion/auth-service:latest
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: AUTH_SERVICE_PORT
            - name: MONGODB_URL
              value: 'mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/$(MONGODB_DATABASE)?authSource=admin'
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGODB_PASSWORD
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: MONGODB_DATABASE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: MAIL_HOST
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: MAIL_USER
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: MAIL_PASS
            - name: BCRYPT_SALT_ROUNDS
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: BCRYPT_SALT_ROUNDS
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
