apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: auth-service
