# Auth Service
# Provides internal network endpoint for authentication service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: studynotion
    component: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: studynotion
    component: auth-service
