apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        component: microservice
    spec:
      containers:
      - name: notification-service
        image: studynotion-notification-service:latest
        ports:
        - containerPort: 3007
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: NODE_ENV
        - name: PORT
          value: "3007"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: JWT_SECRET
        - name: MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: MAIL_HOST
        - name: MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: MAIL_PORT
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MAIL_USER
        - name: MAIL_PASS
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MAIL_PASS
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: API_BASE_URL
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3007
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3007
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
