apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
    name: http
  selector:
    app: notification-service
