apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: studynotion
    component: notification-service
spec:
  type: ClusterIP
  ports:
    - port: 3007
      targetPort: 3007
      protocol: TCP
      name: http
  selector:
    app: studynotion
    component: notification-service
