apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  labels:
    app: studynotion
    component: media-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studynotion
      component: media-service
  template:
    metadata:
      labels:
        app: studynotion
        component: media-service
    spec:
      containers:
        - name: media-service
          image: asxhazard/studynotion-media-service:latest
          ports:
            - containerPort: 3006
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: NODE_ENV
            - name: PORT
              value: '3006'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-credentials
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-credentials
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-credentials
                  key: CLOUDINARY_API_SECRET
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: FRONTEND_URL
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
