apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  labels:
    app: media-service
    component: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
        component: microservice
    spec:
      containers:
      - name: media-service
        image: studynotion-media-service:latest
        ports:
        - containerPort: 3007
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: NODE_ENV
        - name: PORT
          value: "3007"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: JWT_SECRET
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: CLOUDINARY_API_SECRET
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: API_BASE_URL
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 3007
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3007
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
