apiVersion: v1
kind: Service
metadata:
  name: media-service
  labels:
    app: studynotion
    component: media-service
spec:
  type: ClusterIP
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
      name: http
  selector:
    app: studynotion
    component: media-service
