apiVersion: v1
kind: Service
metadata:
  name: media-service
  labels:
    app: media-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 3007
    targetPort: 3007
    protocol: TCP
    name: http
  selector:
    app: media-service
