apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studynotion-ingress
  namespace: studynotion
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
  - hosts:
    - studynotion.example.com
    - api.studynotion.example.com
    secretName: studynotion-tls
  rules:
  - host: studynotion.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: api.studynotion.example.com
    http:
      paths:
      - path: /api/v1/auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /api/v1/course(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: course-service
            port:
              number: 80
      - path: /api/v1/payment(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port:
              number: 80
      - path: /api/v1/profile(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: profile-service
            port:
              number: 80
      - path: /api/v1/rating(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: rating-service
            port:
              number: 80
      - path: /api/v1/media(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: media-service
            port:
              number: 80
      - path: /api/v1/notification(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: notification-service
            port:
              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 80
