apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
        component: frontend
    spec:
      containers:
      - name: frontend-service
        image: studynotion-frontend:latest
        ports:
        - containerPort: 3008
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: NODE_ENV
        - name: PORT
          value: "3008"
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: API_GATEWAY_URL
        - name: VITE_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: API_GATEWAY_URL
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3008
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3008
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
