apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: studynotion
  labels:
    app: frontend-service
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3008
    targetPort: 3008
    protocol: TCP
    name: http
  selector:
    app: frontend-service
