apiVersion: v1
kind: ConfigMap
metadata:
  name: studynotion-config
data:
  NODE_ENV: production
  
  # MongoDB URIs
  MONGODB_URI_AUTH: "mongodb://mongodb-0.mongodb.studynotion.svc.cluster.local:27017/auth"
  MONGODB_URI_COURSE: "mongodb://mongodb-0.mongodb.studynotion.svc.cluster.local:27017/course"
  MONGODB_URI_PAYMENT: "mongodb://mongodb-0.mongodb.studynotion.svc.cluster.local:27017/payment"
  MONGODB_URI_PROFILE: "mongodb://mongodb-0.mongodb.studynotion.svc.cluster.local:27017/profile"
  MONGODB_URI_RATING: "mongodb://mongodb-0.mongodb.studynotion.svc.cluster.local:27017/rating"
  MONGODB_URI_MEDIA: "mongodb://mongodb-0.mongodb.studynotion.svc.cluster.local:27017/media"
  MONGODB_URI_NOTIFICATION: "mongodb://mongodb-0.mongodb.studynotion.svc.cluster.local:27017/notification"
  
  # API Gateway Configuration
  API_GATEWAY_PORT: "3000"
  API_GATEWAY_URL: "http://api-gateway.studynotion.svc.cluster.local:3000"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service.studynotion.svc.cluster.local:3001"
  COURSE_SERVICE_URL: "http://course-service.studynotion.svc.cluster.local:3003"
  PAYMENT_SERVICE_URL: "http://payment-service.studynotion.svc.cluster.local:3002"
  PROFILE_SERVICE_URL: "http://profile-service.studynotion.svc.cluster.local:3004"
  RATING_SERVICE_URL: "http://rating-service.studynotion.svc.cluster.local:3005"
  MEDIA_SERVICE_URL: "http://media-service.studynotion.svc.cluster.local:3007"
  NOTIFICATION_SERVICE_URL: "http://notification-service.studynotion.svc.cluster.local:3006"
  
  # Frontend Configuration
  API_BASE_URL: "https://api.studynotion.example.com"
  FRONTEND_URL: "https://studynotion.example.com"
  
  # Mail Configuration
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  
  # External Services
  CLOUDINARY_CLOUD_NAME: "studynotion-cloud"
  RAZORPAY_KEY_ID: "rzp_test_your_key_id"
