# Kubernetes Secrets for StudyNotion application
# Contains sensitive configuration data that should not be stored in ConfigMaps
# NOTE: In production, use external secret management tools like HashiCorp Vault, AWS Secrets Manager, etc.

# Database credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: default
  labels:
    app: studynotion
    component: database
type: Opaque
data:
  # Base64 encoded values - replace with your actual credentials
  # To encode: echo -n "your-value" | base64
  MONGODB_USERNAME: YWRtaW4=  # admin
  MONGODB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  MONGODB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=  # password123

---
# JWT and authentication secrets
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: default
  labels:
    app: studynotion
    component: auth
type: Opaque
data:
  # Base64 encoded JWT secret - MUST be changed in production
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl  # your-super-secret-jwt-key-here
  JWT_REFRESH_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl  # your-super-secret-jwt-key-here

---
# Email service credentials
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
  namespace: default
  labels:
    app: studynotion
    component: notification
type: Opaque
data:
  # Base64 encoded email credentials - replace with your actual credentials
  MAIL_USER: eW91ci1lbWFpbEBnbWFpbC5jb20=  # your-email@gmail.com
  MAIL_PASS: eW91ci1hcHAtcGFzc3dvcmQ=  # your-app-password

---
# Cloudinary credentials for media service
apiVersion: v1
kind: Secret
metadata:
  name: cloudinary-credentials
  namespace: default
  labels:
    app: studynotion
    component: media
type: Opaque
data:
  # Base64 encoded Cloudinary credentials - replace with your actual credentials
  CLOUDINARY_CLOUD_NAME: eW91ci1jbG91ZC1uYW1l  # your-cloud-name
  CLOUDINARY_API_KEY: eW91ci1hcGkta2V5  # your-api-key
  CLOUDINARY_API_SECRET: eW91ci1hcGktc2VjcmV0  # your-api-secret

---
# Razorpay credentials for payment service
apiVersion: v1
kind: Secret
metadata:
  name: razorpay-credentials
  namespace: default
  labels:
    app: studynotion
    component: payment
type: Opaque
data:
  # Base64 encoded Razorpay credentials - replace with your actual credentials
  RAZORPAY_KEY: eW91ci1yYXpvcnBheS1rZXk=  # your-razorpay-key
  RAZORPAY_SECRET: eW91ci1yYXpvcnBheS1zZWNyZXQ=  # your-razorpay-secret

---
# OAuth credentials
apiVersion: v1
kind: Secret
metadata:
  name: oauth-credentials
  namespace: default
  labels:
    app: studynotion
    component: auth
type: Opaque
data:
  # Base64 encoded OAuth credentials - replace with your actual credentials
  GOOGLE_CLIENT_ID: eW91ci1nb29nbGUtY2xpZW50LWlk  # your-google-client-id
  GOOGLE_CLIENT_SECRET: eW91ci1nb29nbGUtY2xpZW50LXNlY3JldA==  # your-google-client-secret

---
# TLS certificates (if using HTTPS)
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  namespace: default
  labels:
    app: studynotion
    component: ingress
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Replace with your actual certificate files
  tls.crt: LS0tLS1CRUdJTi... # Your TLS certificate
  tls.key: LS0tLS1CRUdJTi... # Your TLS private key

---
# Generic application secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
  labels:
    app: studynotion
    component: general
type: Opaque
data:
  # Additional secrets that might be needed
  # Base64 encoded values
  ENCRYPTION_KEY: ZW5jcnlwdGlvbi1rZXktZm9yLWRhdGE=  # encryption-key-for-data
  SESSION_SECRET: c2Vzc2lvbi1zZWNyZXQtZm9yLWNvb2tpZXM=  # session-secret-for-cookies
