apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: studynotion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: studynotion-auth-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: NODE_ENV
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: MONGODB_URI_AUTH
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: JWT_SECRET
        - name: MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: MAIL_HOST
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MAIL_USER
        - name: MAIL_PASS
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MAIL_PASS
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: FRONTEND_URL
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: studynotion
spec:
  selector:
    app: auth-service
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
