apiVersion: v1
kind: ConfigMap
metadata:
  name: studynotion-config
  namespace: studynotion
data:
  NODE_ENV: "development"
  MAIL_HOST: "smtp.gmail.com"
  FRONTEND_URL: "http://localhost:3008"
  API_BASE_URL: "http://localhost:3000"
  MONGODB_URI_AUTH: "mongodb://studynotion-mongo:27017/auth"
  MONGODB_URI_COURSES: "mongodb://studynotion-mongo:27017/courses"
  MONGODB_URI_PAYMENTS: "mongodb://studynotion-mongo:27017/payments"
  MONGODB_URI_PROFILE: "mongodb://studynotion-mongo:27017/profile"
  MONGODB_URI_RATINGS: "mongodb://studynotion-mongo:27017/ratings"
  MONGODB_URI_NOTIFICATIONS: "mongodb://studynotion-mongo:27017/notifications"
  MONGODB_URI_MEDIA: "mongodb://studynotion-mongo:27017/media"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  COURSE_SERVICE_URL: "http://course-service:3003"
  PAYMENT_SERVICE_URL: "http://payment-service:3002"
  PROFILE_SERVICE_URL: "http://profile-service:3004"
  RATING_SERVICE_URL: "http://rating-service:3005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3006"
  MEDIA_SERVICE_URL: "http://media-service:3007"
