apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: studynotion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: studynotion-frontend:latest
        ports:
        - containerPort: 3008
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: NODE_ENV
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: API_BASE_URL
        - name: VITE_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: API_BASE_URL
        livenessProbe:
          httpGet:
            path: /
            port: 3008
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3008
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: studynotion
spec:
  selector:
    app: frontend
  ports:
  - port: 3008
    targetPort: 3008
  type: LoadBalancer
