apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-auth
  namespace: studynotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-auth
  template:
    metadata:
      labels:
        app: mongodb-auth
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: studynotion-auth
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-auth-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-auth-service
  namespace: studynotion
spec:
  selector:
    app: mongodb-auth
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-auth-pvc
  namespace: studynotion
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
