apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: studynotion
spec:
  selector:
    app: auth-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: studynotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: asxhazard/studynotion-auth-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: NODE_ENV
        - name: PORT
          value: "3001"
        # For production clusters with variable substitution support:
        # - name: MONGODB_URL
        #   value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017/studynotion?authSource=admin"
        # - name: MONGODB_URI
        #   value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017/studynotion?authSource=admin"
        
        # For minikube (hardcoded credentials):
        - name: MONGODB_URL
          value: "mongodb://admin:password123@mongodb:27017/studynotion?authSource=admin"
        - name: MONGODB_URI
          value: "mongodb://admin:password123@mongodb:27017/studynotion?authSource=admin"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MONGO_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRE
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: JWT_EXPIRE
        - name: COOKIE_EXPIRE
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: COOKIE_EXPIRE
        - name: MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: MAIL_HOST
        - name: MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: MAIL_PORT
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MAIL_USER
        - name: MAIL_PASS
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MAIL_PASS
        - name: FRONTEND_URL
          value: "http://frontend:3008"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3007"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
