apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: studynotion
spec:
  selector:
    app: course-service
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: studynotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: asxhazard/studynotion-course-service:latest
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: studynotion-config
              key: NODE_ENV
        - name: PORT
          value: "3003"
        # For Minikube - use hardcoded credentials (variable substitution doesn't work)
        - name: MONGODB_URL
          value: "mongodb://admin:password123@mongodb:27017/studynotion?authSource=admin"
        - name: MONGODB_URI
          value: "mongodb://admin:password123@mongodb:27017/studynotion?authSource=admin"
        # For production clusters - uncomment these and comment above
        # - name: MONGODB_URL
        #   value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017/studynotion?authSource=admin"
        # - name: MONGODB_URI
        #   value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27017/studynotion?authSource=admin"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: MONGO_PASSWORD
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: CLOUDINARY_API_SECRET
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: studynotion-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
