# API Gateway Service
# Exposes API Gateway to external traffic and internal services
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default
  labels:
    app: studynotion
    component: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: studynotion
    component: api-gateway
