apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  labels:
    app: studynotion
    component: profile-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studynotion
      component: profile-service
  template:
    metadata:
      labels:
        app: studynotion
        component: profile-service
    spec:
      containers:
        - name: profile-service
          image: asxhazard/studynotion-profile-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: NODE_ENV
            - name: PORT
              value: '3004'
            - name: MONGODB_URL
              value: 'mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/$(MONGODB_DATABASE)?authSource=admin'
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: MONGODB_PASSWORD
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: MONGODB_DATABASE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: studynotion-config
                  key: FRONTEND_URL
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
