apiVersion: v1
kind: Service
metadata:
  name: profile-service
  labels:
    app: profile-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app: profile-service
