import { endpoints } from './api'

// Auth endpoints
export const authEndpoints = {
  SENDOTP_API: endpoints.AUTH.SENDOTP_API,
  SIGNUP_API: endpoints.AUTH.SIGNUP_API,
  LOGIN_API: endpoints.AUTH.LOGIN_API,
  RESETPASSTOKEN_API: endpoints.AUTH.RESETPASSTOKEN_API,
  RESETPASSWORD_API: endpoints.AUTH.RESETPASSWORD_API,
  CHANGEPASSWORD_API: endpoints.AUTH.CHANGEPASSWORD_API,
}

// Profile endpoints
export const profileEndpoints = {
  GET_USER_DETAILS_API: endpoints.PROFILE.GET_USER_DETAILS_API,
  GET_USER_ENROLLED_COURSES_API: endpoints.PROFILE.GET_USER_ENROLLED_COURSES_API,
  UPDATE_PROFILE_API: endpoints.PROFILE.UPDATE_PROFILE_API,
  UPDATE_DISPLAY_PICTURE_API: endpoints.PROFILE.UPDATE_DISPLAY_PICTURE_API,
  DELETE_PROFILE_API: endpoints.PROFILE.DELETE_PROFILE_API,
  GET_INSTRUCTOR_DATA_API: endpoints.PROFILE.GET_INSTRUCTOR_DATA_API,
}

// Course endpoints
export const courseEndpoints = {
  GET_ALL_COURSE_API: endpoints.COURSE.GET_ALL_COURSE_API,
  COURSE_DETAILS_API: endpoints.COURSE.COURSE_DETAILS_API,
  EDIT_COURSE_API: endpoints.COURSE.EDIT_COURSE_API,
  CREATE_COURSE_API: endpoints.COURSE.CREATE_COURSE_API,
  DELETE_COURSE_API: endpoints.COURSE.DELETE_COURSE_API,
  GET_ALL_INSTRUCTOR_COURSES_API: endpoints.COURSE.GET_INSTRUCTOR_COURSES_API,
  GET_FULL_COURSE_DETAILS_AUTHENTICATED: endpoints.COURSE.GET_FULL_COURSE_DETAILS_AUTHENTICATED,
  LECTURE_COMPLETION_API: endpoints.COURSE.LECTURE_COMPLETION_API,
  CREATE_SECTION_API: endpoints.COURSE.CREATE_SECTION_API,
  CREATE_SUBSECTION_API: endpoints.COURSE.CREATE_SUBSECTION_API,
  UPDATE_SECTION_API: endpoints.COURSE.UPDATE_SECTION_API,
  UPDATE_SUBSECTION_API: endpoints.COURSE.UPDATE_SUBSECTION_API,
  DELETE_SECTION_API: endpoints.COURSE.DELETE_SECTION_API,
  DELETE_SUBSECTION_API: endpoints.COURSE.DELETE_SUBSECTION_API,
  COURSE_CATEGORIES_API: endpoints.CATEGORIES.CATEGORIES_API,
  CREATE_RATING_API: endpoints.RATING.CREATE_RATING_API,
}

// Categories endpoints
export const categories = {
  CATEGORIES_API: endpoints.CATEGORIES.CATEGORIES_API,
  CREATE_CATEGORY_API: endpoints.CATEGORIES.CREATE_CATEGORY_API,
  CATEGORY_PAGE_DETAILS_API: endpoints.CATEGORIES.CATEGORY_PAGE_DETAILS_API,
}

// Rating endpoints
export const ratingEndpoints = {
  REVIEWS_DETAILS_API: endpoints.RATING.REVIEWS_DETAILS_API,
  CREATE_RATING_API: endpoints.RATING.CREATE_RATING_API,
  GET_AVERAGE_RATING_API: endpoints.RATING.GET_AVERAGE_RATING_API,
}

// Student endpoints (payment removed)
export const studentEndpoints = {
  // Payment functionality removed - courses are now free
}

// Contact endpoints
export const contactusEndpoint = {
  CONTACT_US_API: endpoints.CONTACT.CONTACT_US_API,
}

// Settings endpoints
export const settingsEndpoints = {
  UPDATE_DISPLAY_PICTURE_API: endpoints.PROFILE.UPDATE_DISPLAY_PICTURE_API,
  UPDATE_PROFILE_API: endpoints.PROFILE.UPDATE_PROFILE_API,
  CHANGE_PASSWORD_API: endpoints.AUTH.CHANGEPASSWORD_API,
  DELETE_PROFILE_API: endpoints.PROFILE.DELETE_PROFILE_API,
}
